export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const FAVORITES_FROM_LOCAL_STORAGE = 'FAVORITES_FROM_LOCAL_STORAGE';
export const FAVORITE_CARD_CHANGE_ORDER = 'FAVORITE_CARD_CHANGE_ORDER';