export const SET_JOKES = 'SET_JOKES';
export const PAGINATE_PAGE_NUMBER = 'PAGINATE_PAGE_NUMBER';
export const CURRENT_PAGE = 'CURRENT_PAGE';
export const CLEAR_JOKES = 'CLEAR_JOKES';
export const ADD_NEW_FAVORITE = 'ADD_NEW_FAVORITE';
export const CLEAR_NEW_FAVORITE = 'CLEAR_NEW_FAVORITE';
