export const SET_JOKES = 'SET_JOKES';
export const PAGINATE_PAGE_NUMBER = 'PAGINATE_PAGE_NUMBER';
export const CURRENT_PAGE_ACTION = 'CURRENT_PAGE_ACTION';
export const CLEAR_JOKES_ACTION = 'CLEAR_JOKES_ACTION';
